-- Migration: Add scheduled_time to orders and Create order_messages for Chat
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS scheduled_time TIMESTAMP WITH TIME ZONE;

CREATE TABLE IF NOT EXISTS public.order_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    sender_name TEXT,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable RLS for messages (For now public read/insert for testing)
ALTER TABLE public.order_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Messages" ON public.order_messages FOR SELECT USING (true);
CREATE POLICY "Public Insert Messages" ON public.order_messages FOR INSERT WITH CHECK (true);
