-- ============================================
-- INGREDIENT / RECIPE STOCK SYSTEM
-- Run this in Supabase SQL Editor
-- ============================================

-- 1. INGREDIENTS TABLE (presas de pollo, pan, etc.)
CREATE TABLE IF NOT EXISTS public.ingredients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,                  -- "Presa de Pollo 1/8", "Pan de hamburguesa"
  unit TEXT DEFAULT 'unidad',          -- "unidad", "kg", "litro"
  stock INTEGER DEFAULT 0,            -- Current stock
  min_stock INTEGER DEFAULT 5,        -- Minimum alert threshold
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. PRODUCT RECIPES (which ingredients each product uses)
CREATE TABLE IF NOT EXISTS public.product_ingredients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  ingredient_id BIGINT REFERENCES public.ingredients(id) ON DELETE CASCADE,
  quantity INTEGER NOT NULL DEFAULT 1,  -- How many units of this ingredient per product
  UNIQUE(product_id, ingredient_id)
);

-- 3. TRIGGER: Deduct ingredients when an order item is inserted
CREATE OR REPLACE FUNCTION public.handle_ingredient_deduction()
RETURNS TRIGGER AS $$
BEGIN
    -- Deduct ingredient stock based on recipe
    UPDATE public.ingredients i
    SET stock = i.stock - (pi.quantity * NEW.quantity)
    FROM public.product_ingredients pi
    WHERE pi.product_id = NEW.product_id
      AND pi.ingredient_id = i.id;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS after_order_item_deduct_ingredients ON public.order_items;
CREATE TRIGGER after_order_item_deduct_ingredients
AFTER INSERT ON public.order_items
FOR EACH ROW
EXECUTE FUNCTION public.handle_ingredient_deduction();

-- 4. TRIGGER: Restore ingredients when an order item is deleted
CREATE OR REPLACE FUNCTION public.handle_ingredient_restoration()
RETURNS TRIGGER AS $$
BEGIN
    -- Restore ingredient stock based on recipe
    UPDATE public.ingredients i
    SET stock = i.stock + (pi.quantity * OLD.quantity)
    FROM public.product_ingredients pi
    WHERE pi.product_id = OLD.product_id
      AND pi.ingredient_id = i.id;

    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS after_order_item_restore_ingredients ON public.order_items;
CREATE TRIGGER after_order_item_restore_ingredients
AFTER DELETE ON public.order_items
FOR EACH ROW
EXECUTE FUNCTION public.handle_ingredient_restoration();

-- 5. RLS POLICIES
ALTER TABLE public.ingredients ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Ingredients" ON public.ingredients FOR SELECT USING (true);
CREATE POLICY "Admin Insert Ingredients" ON public.ingredients FOR INSERT WITH CHECK (true);
CREATE POLICY "Admin Update Ingredients" ON public.ingredients FOR UPDATE USING (true);
CREATE POLICY "Admin Delete Ingredients" ON public.ingredients FOR DELETE USING (true);

ALTER TABLE public.product_ingredients ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Recipes" ON public.product_ingredients FOR SELECT USING (true);
CREATE POLICY "Admin Insert Recipes" ON public.product_ingredients FOR INSERT WITH CHECK (true);
CREATE POLICY "Admin Update Recipes" ON public.product_ingredients FOR UPDATE USING (true);
CREATE POLICY "Admin Delete Recipes" ON public.product_ingredients FOR DELETE USING (true);

-- 6. ENABLE REALTIME (optional, for live stock updates)
ALTER PUBLICATION supabase_realtime ADD TABLE public.ingredients;
