-- MASTER FIX for HEHA Premium Kiosk
-- Run this in Supabase SQL Editor

-- 1. Profiles: Update roles to allow 'cliente' and fix RLS
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_role_check;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_role_check 
CHECK (role IN ('admin', 'cajero', 'kiosco', 'cliente'));

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;
CREATE POLICY "Users can insert own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;
CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id OR EXISTS (SELECT 1 FROM public.profiles p2 WHERE p2.id = auth.uid() AND p2.role IN ('admin', 'cajero')));

DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- 2. Orders: Ensure columns exist for Reservations and Customer Names
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS scheduled_time TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS customer_name TEXT;

-- 3. Messages: Ensure table and policies exist (order_id NULL means General Chat)
CREATE TABLE IF NOT EXISTS public.order_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE NULL,
    sender_name TEXT,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.order_messages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read Messages" ON public.order_messages;
CREATE POLICY "Public Read Messages" ON public.order_messages FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public Insert Messages" ON public.order_messages;
CREATE POLICY "Public Insert Messages" ON public.order_messages FOR INSERT WITH CHECK (true);
