-- HEHA Multi-Branch Core Migration
-- Run this in the Supabase SQL Editor

-- 1. Create Branches Table
CREATE TABLE IF NOT EXISTS public.branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT,
    phone TEXT,
    city TEXT DEFAULT 'La Paz',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Create Branch Products (Branch-specific Stock & Price)
CREATE TABLE IF NOT EXISTS public.branch_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES public.branches(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    stock INTEGER DEFAULT 0,
    price DECIMAL(10, 2) NOT NULL,
    is_available BOOLEAN DEFAULT true,
    track_stock BOOLEAN DEFAULT false,
    UNIQUE(branch_id, product_id)
);

-- 3. Link Users to Branches
CREATE TABLE IF NOT EXISTS public.profile_branches (
    profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    branch_id BIGINT REFERENCES public.branches(id) ON DELETE CASCADE,
    PRIMARY KEY (profile_id, branch_id)
);

-- 4. Add branch_id to operational tables
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS branch_id BIGINT REFERENCES public.branches(id);
ALTER TABLE public.cash_register ADD COLUMN IF NOT EXISTS branch_id BIGINT REFERENCES public.branches(id);
ALTER TABLE public.cash_moves ADD COLUMN IF NOT EXISTS branch_id BIGINT REFERENCES public.branches(id);
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS branch_id BIGINT REFERENCES public.branches(id);
ALTER TABLE public.order_messages ADD COLUMN IF NOT EXISTS branch_id BIGINT REFERENCES public.branches(id);
ALTER TABLE public.ingredients ADD COLUMN IF NOT EXISTS branch_id BIGINT REFERENCES public.branches(id);

-- 5. INITIAL MIGRATION LOGIC
DO $$
DECLARE
    default_branch_id BIGINT;
BEGIN
    -- Create the default branch if it doesn't exist
    INSERT INTO public.branches (name, city) 
    VALUES ('Sucursal Matriz', 'La Paz') 
    ON CONFLICT DO NOTHING;

    -- Get the ID of the default branch
    SELECT id INTO default_branch_id FROM public.branches WHERE name = 'Sucursal Matriz' LIMIT 1;

    -- Migrate current products to branch_products
    INSERT INTO public.branch_products (branch_id, product_id, stock, price, is_available, track_stock)
    SELECT default_branch_id, id, stock, price, is_available, COALESCE(track_stock, false)
    FROM public.products
    ON CONFLICT (branch_id, product_id) DO NOTHING;

    -- Update existing records to the default branch
    UPDATE public.orders SET branch_id = default_branch_id WHERE branch_id IS NULL;
    UPDATE public.cash_register SET branch_id = default_branch_id WHERE branch_id IS NULL;
    UPDATE public.cash_moves SET branch_id = default_branch_id WHERE branch_id IS NULL;
    UPDATE public.expenses SET branch_id = default_branch_id WHERE branch_id IS NULL;
    UPDATE public.order_messages SET branch_id = default_branch_id WHERE branch_id IS NULL;
    UPDATE public.ingredients SET branch_id = default_branch_id WHERE branch_id IS NULL;

    -- Assign all current profiles to the default branch
    INSERT INTO public.profile_branches (profile_id, branch_id)
    SELECT id, default_branch_id FROM public.profiles
    ON CONFLICT DO NOTHING;

END $$;

-- 6. Update Triggers for Ingredients (to be branch-aware)
CREATE OR REPLACE FUNCTION public.handle_ingredient_deduction()
RETURNS TRIGGER AS $$
DECLARE
    v_branch_id BIGINT;
BEGIN
    SELECT branch_id INTO v_branch_id FROM public.orders WHERE id = NEW.order_id;

    UPDATE public.ingredients i
    SET stock = i.stock - (pi.quantity * NEW.quantity)
    FROM public.product_ingredients pi
    WHERE pi.product_id = NEW.product_id
      AND pi.ingredient_id = i.id
      AND i.branch_id = v_branch_id;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.handle_ingredient_restoration()
RETURNS TRIGGER AS $$
DECLARE
    v_branch_id BIGINT;
BEGIN
    SELECT branch_id INTO v_branch_id FROM public.orders WHERE id = OLD.order_id;

    UPDATE public.ingredients i
    SET stock = i.stock + (pi.quantity * OLD.quantity)
    FROM public.product_ingredients pi
    WHERE pi.product_id = OLD.product_id
      AND pi.ingredient_id = i.id
      AND i.branch_id = v_branch_id;

    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

-- 7. Enable RLS and basic policies for branches
ALTER TABLE public.branches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Branches" ON public.branches FOR SELECT USING (true);
CREATE POLICY "Admin All Branches" ON public.branches FOR ALL TO authenticated USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
);

ALTER TABLE public.branch_products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Branch Products" ON public.branch_products FOR SELECT USING (true);
CREATE POLICY "Admin All Branch Products" ON public.branch_products FOR ALL TO authenticated USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
);

ALTER TABLE public.profile_branches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own branches" ON public.profile_branches FOR SELECT USING (auth.uid() = profile_id);
CREATE POLICY "Admin All Profile Branches" ON public.profile_branches FOR ALL TO authenticated USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
);
