-- Multi-branch Migration Setup
-- 1. Create Branches Table
CREATE TABLE IF NOT EXISTS public.branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT,
    phone TEXT,
    city TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Branch Products (Stock & Price per Branch)
CREATE TABLE IF NOT EXISTS public.branch_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES public.branches(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    stock INTEGER DEFAULT 0,
    price DECIMAL(10, 2) NOT NULL,
    is_available BOOLEAN DEFAULT true,
    track_stock BOOLEAN DEFAULT false,
    UNIQUE(branch_id, product_id)
);

-- 3. Add Branch ID to Orders
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS branch_id BIGINT REFERENCES public.branches(id);

-- 4. Add Branch ID to Users (Profiles)
-- Assuming a 'profiles' table exists or adding to 'users' metadata
-- For simplicity in this demo, we'll assume we can use a metadata field or a dedicated table.
CREATE TABLE IF NOT EXISTS public.user_branches (
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    branch_id BIGINT REFERENCES public.branches(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, branch_id)
);

-- 5. Create a Default Branch
INSERT INTO public.branches (name, city) VALUES ('Sucursal Matriz', 'La Paz') ON CONFLICT DO NOTHING;

-- 6. Initial Migration of Stock/Prices to the default branch
-- (This should be run after the above steps and after verifying the default branch ID)
DO $$
DECLARE
    default_branch_id BIGINT;
BEGIN
    SELECT id INTO default_branch_id FROM public.branches LIMIT 1;
    
    INSERT INTO public.branch_products (branch_id, product_id, stock, price, is_available, track_stock)
    SELECT default_branch_id, id, stock, price, is_available, track_stock
    FROM public.products
    ON CONFLICT (branch_id, product_id) DO NOTHING;
END $$;
