-- RUN THIS IN SUPABASE SQL EDITOR

-- 1. Profiles (Managed by Supabase Auth usually, but we extend it or just use metadata)
-- For simplicity in this POS, we will use a 'cashiers' table or just manage users via Auth.
-- Let's create a profiles table.
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  role TEXT DEFAULT 'cajero' CHECK (role IN ('admin', 'cajero')),
  full_name TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Products
-- Optional: Separate Categories Table for dynamic management
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Insert default categories if empty
INSERT INTO public.categories (name)
SELECT 'General'
WHERE NOT EXISTS (SELECT 1 FROM public.categories); -- Minimal default, user can add more

CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  cost DECIMAL(10,2) NOT NULL DEFAULT 0,
  category TEXT DEFAULT 'General', -- Storing name for simplicity or we could link to ID
  description TEXT,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Add category if it doesn't exist (Manual run required for existing DB)
-- ALTER TABLE public.products ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'General';

-- 3. Orders
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  total_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  order_type TEXT NOT NULL CHECK (order_type IN ('mesa', 'llevar', 'whatsapp')),
  status TEXT DEFAULT 'completed' CHECK (status IN ('pending', 'completed', 'cancelled')),
  payment_method TEXT DEFAULT 'cash',
  
  -- Delivery details
  customer_phone TEXT,
  delivery_location TEXT,
  advance_amount DECIMAL(10,2) DEFAULT 0, -- New field for Adelanto
  
  -- Metadata
  cashier_name TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. Order Items
CREATE TABLE IF NOT EXISTS public.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id),
  quantity INTEGER NOT NULL DEFAULT 1,
  price_at_sale DECIMAL(10,2) NOT NULL, -- Price at the moment of sale
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. Cash Register Sessions
CREATE TABLE IF NOT EXISTS public.cash_register (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opened_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  closed_at TIMESTAMP WITH TIME ZONE,
  initial_cash DECIMAL(10,2) DEFAULT 0,
  final_cash DECIMAL(10,2),
  total_sales_digital DECIMAL(10,2) DEFAULT 0, -- QR, Transfer
  status TEXT DEFAULT 'open', -- open, closed
  user_id UUID REFERENCES auth.users(id)
);

-- 6. Cash Moves (Retiros/Ingresos)
CREATE TABLE IF NOT EXISTS public.cash_moves (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cash_register_id BIGINT REFERENCES public.cash_register(id),
  type TEXT NOT NULL CHECK (type IN ('withdrawal', 'deposit')), -- withdrawal = retiro, deposit = ingreso extra
  amount DECIMAL(10,2) NOT NULL,
  reason TEXT,
  performed_by TEXT, -- Admin name or User ID
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable RLS (Row Level Security) - Optional for internal tool but good practice
-- For now we allow public access to speed up dev (Modify policies for production!)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Products" ON public.products FOR SELECT USING (true);
CREATE POLICY "Admin Insert Products" ON public.products FOR INSERT WITH CHECK (true); -- TODO: Lock down
CREATE POLICY "Admin Update Products" ON public.products FOR UPDATE USING (true);
CREATE POLICY "Admin Delete Products" ON public.products FOR DELETE USING (true);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Orders" ON public.orders FOR SELECT USING (true);
CREATE POLICY "Public Insert Orders" ON public.orders FOR INSERT WITH CHECK (true);

ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Items" ON public.order_items FOR SELECT USING (true);
CREATE POLICY "Public Insert Items" ON public.order_items FOR INSERT WITH CHECK (true);

-- Seed Data (Initial Products)
INSERT INTO public.products (name, price, cost, description, image_url) VALUES 
('Hamburguesa Clásica', 25.0, 15.0, 'Carne de res 150g, lechuga, tomate, salsa especial', 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500'),
('Papas Fritas Grandes', 15.0, 8.0, 'Papas crocantes con sal', 'https://images.unsplash.com/photo-1573080496987-a199f8cd4054?w=500'),
('Pollo Broaster (Cuarto)', 28.0, 18.0, 'Cuarto de pollo con arroz y papas', 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=500'),
('Refresco 500ml', 8.0, 4.0, 'Coca-Cola, Fanta o Sprite', 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500');
